#!/bin/bash
# debugip: run tcpdump to display packets for debugging ip
#
# Copyright (c) 2011 Grant Bowman http://grantbow.com/
#
# Version 0.1

NETIF=wlan0

# from BLFS
NORMAL="\[\e[0m\]"
RED="\[\e[1;31m\]"
GREEN="\[\e[1;32m\]"
BLUE="\[\e[1;34m\]"
GREY="\[\e[1;30m\]"

# -l Make stdout line buffered.
# -n Don't convert addresses
# -v verbose
# only show packets arriving at or departing from this host

echo "$GREY***** running command$ $NORMAL sudo tcpdump -l -n -v -i $NETIF host `hostname -I` "
sudo tcpdump -l -n -v -i "$NETIF" host `hostname -I`

