#!/bin/bash

# script purge-old-kernels
# script written by: Grant Bowman <grantbow@ubuntu.com>
# script Version 1.1
# copyright 2010
# Licensed under the GPL v2 or greater

# runs apt-get purge on old linux-image packages and their headers
# This script could easily be modified for other systems
# however it has only been tested on Ubuntu 9.10 Karmic Koala
# Information about other systems would be most appreicated.

kernels=`dpkg -l | egrep ^ii.*linux-image-\[23\] | cut --d=" " --fields=3 | cut --d="-" --fields=3-4`
anyprocessed=0

if (( $EUID )) ; then
    echo "Warning: not run with root privileges. Kernels can not be purged. Rerun with \" sudo !!\"";
fi

for kernel in $kernels ; do
    if [[ ( $kernel-generic != `uname -r` ) && ( $kernel-generic < `uname -r` ) ]] ; then
        # don't offer to remove the currently running or newer  kernels
        anyprocessed=1
        echo -e " ***** Do you want to run the following command? [Y/n] \n apt-get purge linux-image-$kernel-generic linux-headers-$kernel linux-headers-$kernel-generic \n *****";
        $L = `line`;
        if [ $L == "y" ] || [ $L == "" ] ; then
            echo "apt-get purge linux-image-$kernel-generic linux-headers-$kernel linux-headers-$kernel-generic";
        fi
    fi
done

if ! (( $anyprocessed )) ; then
    echo "No old kernels found.";
fi


# takes care of kernels? via comments from http://www.omgubuntu.co.uk/2011/07/kernel-entries-gone/
#
# dpkg -l 'linux-*' | sed '/^ii/!d;/'"$(uname -r | sed "s/\(.*\)-\([^0-9]\+\)/\1/")"'/d;s/^[^ ]* [^ ]* \([^ ]*\).*/\1/;/[0-9]/!d' | xargs sudo apt-get -y purge

