#!/bin/bash
#
# timeleft      Counting down an event
#
# Author:	Grant Bowman <grantbow@grantbow.com>
#
# Version:	0.1  2011-09-04  grantbow@grantbow.com
#

set -e

NAME="timeleft"
DESC="Counting down an event"

SECONDS=`date +%s`            # current
LASTSECONDS=`date --date="Sept 6 06:00:00 PDT 2011" +%s`

echo "`dc -e \" 2 k $LASTSECONDS $SECONDS - 3600 / n \"` hours "

        # use dc to give the difference between two second values (replace variables):
        #
        #       dc -e " 2 k $SECONDS $LASTSECONDS - 3600 / n"
        #
        # use this to give the seconds of any --date (replace string):
        #
        #       date --date="Jun 28 19:38:15 PDT 2003" +%s
        #
        # use this to convert epoch seconds back using local time zone (replace 946684800):
        #
        #       date -d '1970-01-01 UTC 946684800 seconds' +"%Y-%m-%d T %T%z"
        #
        # use this to create an hour of day value
        #
        #       dc -e " 2 k `date +\"%M\"` 60 / n "
        #

