#!/bin/bash
#
#   upt - show just the system uptime, days, hours, and minutes
#   http://tldp.org/HOWTO/Bash-Prompt-HOWTO/x758.html

upSeconds=`cat /proc/uptime | egrep -wo ^[0-9]* `
secs=$(( ${upSeconds} % 60 ))
mins=$(( ${upSeconds} / 60 % 60 ))
hours=$(( ${upSeconds} / 3600 % 24 ))
days=$(( ${upSeconds} / 86400 ))
if [ "${days}" -ne "0" ]
then
   echo -n "${days}d"
fi
echo "${hours}h${mins}m"

